import { describe, it, expect } from 'vitest';
import { RANK_OPTIONS, AGENCY_OPTIONS } from '@/types';

describe('Form field constants', () => {
  it('RANK_OPTIONS has all 45 values', () => {
    expect(RANK_OPTIONS.length).toBe(45);
    const values = RANK_OPTIONS.map((r) => r.value);
    expect(values).toContain('ADM');
    expect(values).toContain('VADM');
    expect(values).toContain('RADM');
    expect(values).toContain('COMO');
    expect(values).toContain('CAPT');
    expect(values).toContain('CDR');
    expect(values).toContain('LCDR');
    expect(values).toContain('LT');
    expect(values).toContain('LTJG');
    expect(values).toContain('ENS');
    expect(values).toContain('GEN');
    expect(values).toContain('LTGEN');
    expect(values).toContain('MGEN');
    expect(values).toContain('BGEN');
    expect(values).toContain('COL');
    expect(values).toContain('LTC');
    expect(values).toContain('MAJ');
    expect(values).toContain('CPT');
    expect(values).toContain('1LT');
    expect(values).toContain('2LT');
    expect(values).toContain('FOIC');
    expect(values).toContain('MCPO');
    expect(values).toContain('SCPO');
    expect(values).toContain('CPO');
    expect(values).toContain('PO1');
    expect(values).toContain('PO2');
    expect(values).toContain('PO3');
    expect(values).toContain('SA');
    expect(values).toContain('SN');
    expect(values).toContain('SR');
    expect(values).toContain('CMSG');
    expect(values).toContain('SMSG');
    expect(values).toContain('MSG');
    expect(values).toContain('TSG');
    expect(values).toContain('SSG');
    expect(values).toContain('SGT');
    expect(values).toContain('CPL');
    expect(values).toContain('PFC');
    expect(values).toContain('PVT');
    expect(values).toContain('OW');
    expect(values).toContain('EW');
    expect(values).toContain('MR');
    expect(values).toContain('MS');
    expect(values).toContain('MRS');
    expect(values).toContain('GDN');
  });

  it('AGENCY_OPTIONS has all 24 values', () => {
    expect(AGENCY_OPTIONS.length).toBe(24);
    const values = AGENCY_OPTIONS.map((a) => a.value);
    expect(values).toContain('LBP');
    expect(values).toContain('DBP');
    expect(values).toContain('PVB');
    expect(values).toContain('ACDI');
    expect(values).toContain('ACES');
    expect(values).toContain('AFPFCMPC');
    expect(values).toContain('AFPMBAI');
    expect(values).toContain('AFPSLAI');
    expect(values).toContain('AGFO');
    expect(values).toContain('ALIP');
    expect(values).toContain('AMWSLAI');
    expect(values).toContain('AVACC');
    expect(values).toContain('BABSLAI');
    expect(values).toContain('BOT B4 ACCT (101)');
    expect(values).toContain('CWSLA');
    expect(values).toContain('FABSLAI');
    expect(values).toContain('KBKP');
    expect(values).toContain('KKMPC');
    expect(values).toContain('PAFCPIC');
    expect(values).toContain('PNSLAI');
    expect(values).toContain('PNRA-CCI');
    expect(values).toContain('PVB EMER LOAN');
    expect(values).toContain('RSBS 5% OF DIFFL');
    expect(values).toContain('RSBS 5% OF REG RATE');
  });
});
